import Navigation from "@/components/Navigation";
import { GlobalContextProvider } from "@/context/GlobalContext";
import AuthContextProvider from "@/context/store/AuthContext";
import { FinanceContextProvider } from "@/context/store/FinanceContext";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import ToastifyProvider from "@/components/toastify/ToastifyProvider";
import HomePage from "@/components/HomePage";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <GlobalContextProvider>
            <FinanceContextProvider>
              <ToastifyProvider />
              <div className="flex flex-row flex-nowrap">
                <Navigation className="min-w-[200px]" />
                <div className="pl-64 flex-grow">{children}</div>
              </div>
            </FinanceContextProvider>
          </GlobalContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
